name: mvn_test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check_format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Check format
        run: mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

  test_klein_common:
    needs: check_format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Maven Test
        run: mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
          && mvn --projects klein-common test
          
  test_klein_spi:
    needs: check_format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Maven Test
        run: mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
          && mvn --projects klein-spi test
                    
  test_klein_rpc:
    needs: check_format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Maven Test
        run: mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
          && mvn --projects klein-rpc test
                    
  test_klein_storage:
    needs: check_format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Maven Test
        run: mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
          && mvn --projects klein-storage test
                    
  test_klein_consensus:
    needs: check_format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Maven Test
        run: mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
          && mvn --projects klein-consensus test
                    
  test_klein_core:
    needs: check_format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Maven Test
        run: mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
          && mvn --projects klein-core test
                    
